beshu-tech/readonlyrest-docs

elasticsearch.md

To add documentation for recent accepted pull request on readonlyrest

Added documentation for QueryAuditLogSerializer

---

elasticsearch.md

Adds docs for https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/410

Added config examples for http_connection_settings

---

commercial.md
kibana.md

Minor changes on trial period dates

Minor changes on trial period dates

---

elasticsearch.md

Added rollup actions to action list

---

elasticsearch.md

🚀New (ES) Example projects with custom audit log serializers

changed: custom audit log serializer documentation

---

kibana.md

Added info about RoR working either with a reverse proxy or without o…ne but not both at the same time

RoR with reverse proxy info

---

elasticsearch.md

log4j2 config

---

elasticsearch.md

[don't merge until release of ROR 1.23.0]

[RORDEV-338] New (ES) introduced must_involve_indices option for indices rule

---

elasticsearch.md

[don't merge until release of ROR 1.23.0]

[RORDEV-331]: headers rule negation support

---

elasticsearch.md

To unlock all actions through kibana as noted in:
https://forum.readonlyrest.com/t/unable-to-delete-index-in-kibana-ui-as-admin/1168/8

Add note on unrestricted kibana user

---

kibana.md

Updated to show support for direct download links for specific version of plugin and  Elasticsearch.

Update kibana.md to show direct download links

---

elasticsearch.md

[don't merge before release of ROR 1.25.0]
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/651

[ROR 1.25.0][RORDEV-365] auth_key_pbkdf2 description

---

elasticsearch.md

I don't know if such description is enough. I will think in the meantime how can I improve it. If you have some ideas please let me know

[RORDEV-356] filter fields not matching ror requests

---

elasticsearch.md

Adding documentation for https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/800

RORDEV-644 groups_and in LDAP

---

changelog.md

The new version support Elasticsearch 8.2.2

RORDEV-683 new version support Elasticsearch 8.2.2

---

kibana.md

- Provide info about new kibana_custom_js_inject_file kibana.yml property

RORDEV-715 Provide info about new kibana_custom_js_inject_file kibana.yml property

---

changelog.md

- Update changelog by kbn 8.4.2 support

Update changelog by kbn 8.4.2 support

---

elasticsearch.md

ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/846

[RORDEV-731] dynamic variables docs improvements + Internode SSL new settings

---

changelog.md

- New version support Elasticsearch 8.4.3

RORDEV-749 new version support Elasticsearch 8.4.3

---

changelog.md

- new version support Elasticsearch 7.17.7

RORDEV-764  new version support Elasticsearch 7.17.7

---

changelog.md

- new version support Elasticsearch 8.5.0

RORDEV-769_new_version_support_Elasticsearch_8.5.0

---

changelog.md

- 8.5.1 and 8.5.2 kibana support

RORDEV-784_new_version_support_Elasticsearch_8.5.2

---

details/authorization-rules-details.md
elasticsearch.md

🚀New (ES) Added groups_and mode to [groups_provider_authorization](https://docs.readonlyrest.com/elasticsearch#groups_provider_authorization) rule
🧐Enhancement (ES) all authorization rules support wildcards in group names

[RORDEV-654][ROREV-770] authorization rules doc improvements

---

changelog.md

RORDEV-793 new version support 8.5.3

---

changelog.md

RORDEV-828 Kibana 8.6.0 support

---

kibana.md

- Provide info about regular expressions in the `kibana_hide_apps`

RORDEV-634 Provide a info about regular expressions in the `kibana_hide_apps`

---

changelog.md

RORDEV-841_Kibana_8.6.1_support

---

changelog.md

RORDEV-843 Kibana 7.17.9 support

---

changelog.md

RORDEV-853 Kibana 8.6.2 support

---

elasticsearch.md

* reorganizing the `rules` section
* improvements in `authentication & authorization` rules section
* added missing kibana-related rules

Refactoring

---

changelog.md

RORDEV-870 Kibana 8.7.0 support

---

details/groups-rule-mapping.md

ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/907

[RORDEV-899] wildcards support in external to local groups mapping

---

kibana.md

- provide management hide apps documentation

Rordev 857 provide management hide apps documentation

---

kibana.md

- Provide automatic migration_of indexes when using multi-tenancy info

RORDEV-898_Provide_automatic_migration_of_indexes_when_using_multi-tenancy

---

changelog.md

- Kibana 8.8.2 and 7.17.11 support

RORDEV-928 Kibana 8.8.2 and 7.17.11 support

---

.gitbook/assets/ReadonlyREST-api.yml

- Changes related to the ReadonlyREST API settings endpoints
- Add additional Enterprise info tag

Rordev 854 changes related to the license

---

universal-builds/universal-builds.md

- Until we introduce the new license endpoint, we need to adjust the docs to the existing state

update license endpoint url

---

changelog.md

RORDEV-963 7.17.12_and 8.9.0 support

---

kibana/readonlyrest-api.md

update ReadonlyREST api url

---

changelog.md
examples/elastic-cloud-cluster-integration/details.md
examples/multitenancy_guide.md
examples/multiuser_guide.md
examples/saml-sso/azure_ad.md
kibana.md

- Provide info that cookiePass is a required kibana.yml property from version 1.51.0

RORDEV 976 Provide info that cookiePass is a required kibana.yml property

---

changelog.md

-  Kibana 8.10.1 and 8.10.2 support

RORDEV-998 Kibana 8.10.1 and 8.10.2 support

---

elasticsearch.md

alert_message-position-fix

---

.gitbook/assets/ReadonlyREST-api.yml
universal-builds/universal-builds.md

- provide activate license endpoint to the ReadonlyREST API

Rordev 966 provide activate license endpoint to the ReadonlyREST API

---

examples/saml-sso/azure_ad.md

- provide required logoutUrl to the docs

Update saml azure docs

---

changelog.md

7.17.15 support

---

changelog.md

RORDEV-1058 Kibana 8.11.2 support

---

changelog.md

-kibana-7.17.16-8.11.3-support

RORDEV-1061_1063-kibana-7.17.16-8.11.3-support

---

kibana.md

- Automatic Session cleanup description

RORDEV-1025 clean stale sessions in case of index based sessions

---

changelog.md

RORDEV-1077 Kibana 8.11.4 support

---

examples/oidc-sso/keycloak_oidc.md

- Provide proxy option to OIDC

RORDEV-1035 provide proxy URL value

---

changelog.md

- RORDEV-1081 kibana 8.12.0 support

---

universal-builds/universal-builds.md

provide retrieval mode info

---

elasticsearch.md

ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/991

[RORDEV-1092] added info about hostname verification

---

kibana.md

- provide info about loading logo from a file

provide info about loading logo from a file

---

changelog.md

RORDEV-1136,1138 8.13.0, 7.17.19 support

---

changelog.md

Rordev-1146 kibana 8.13.1 support

---

changelog.md

- RORDEV-1159 kibana 8.13.2 support

RORDEV-1159 kibana 8.13.2 support

---

kibana.md

- Provide info on how to embed the dashboard and visualization and use JWT
- Provide info about injecting JS and CSS to the login page, via files
- Provide and info about Tenant index configuration

Documentation updates

---

changelog.md

RORDEV-1216 Kibana 7.17.22 support

---

changelog.md

RORDEV-1248-Kibana-7.17.23-support

---

changelog.md

RORDEV-1253 Kibana 8.15.0 support

---

kibana.md

- update Kibana 8.15.0 node path based on the OS

update kibana 8.15.0 node path based on the OS

---

changelog.md

RORDEV-1270 Kibana-8.15.1 support

---

examples/oidc-sso/README.md
examples/oidc-sso/keycloak_oidc.md

- provide authentication methods and possible options

RORDEV-1255 provide authentication methods and possible options

---

kibana.md

- update Client Authentication Methods readability

update Client Authentication Methods readability

---

changelog.md

RORDEV-1290-Kibana-8.15.2-support

---

changelog.md

RORDEV-1308 Kibana 8.15.3 support

---

kibana.md
kibana/readonlyrest-api.md

More license badges

---

changelog.md

RORDEV-1311 Kibana 7.17.25 support

---

kibana.md

There was a wrong page opened on the link click

update upgrading links

---

kibana.md

- Provide Patcher acknowledgement silent mode description

RORDEV-1318 Patcher acknowledgement

---

eck.md
kibana.md

update kbn patching variable

---

changelog.md

RORDEV-1325 Kibana 8.15.4 support

---

changelog.md

RORDEV-1350 Kibana 7.17.26 support
